DROP TABLE OPSKRIFTTEKST;
DROP TABLE OPSKRIFTSBILLEDE;
DROP TABLE OPSKRIFT;
DROP TABLE KOGEBOG;
DROP TABLE FORFATTER;
DROP TABLE KATEGORI;
DROP TABLE HOVEDINGREDIENS;
DROP TABLE BRUGER;

Drop sequence TEKST_ID_SEQUENCE;
Drop sequence BILLEDE_ID_SEQUENCE;
Drop sequence OPSKRIFT_ID_SEQUENCE;
Drop sequence KOGE_ID_SEQUENCE;
Drop sequence FORFATTER_ID_SEQUENCE;
Drop sequence KAT_ID_SEQUENCE;
Drop sequence HI_ID_SEQUENCE;
Drop sequence BRUGER_ID_SEQUENCE;

Create Sequence BRUGER_ID_SEQUENCE START WITH -1 INCREMENT BY 1 MINVALUE -2;
CREATE SEQUENCE HI_ID_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE KAT_ID_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FORFATTER_ID_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE KOGE_ID_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE OPSKRIFT_ID_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BILLEDE_ID_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TEKST_ID_SEQUENCE START WITH 1 INCREMENT BY 1;

Create table BRUGER(
BRUGER_ID int PRIMARY KEY,
FORNAVN VARCHAR2(20) NOT NULL,
EFTERNAVN VARCHAR2(20) NOT NULL,
PASSWORD VARCHAR2(10) NOT NULL
);
CREATE TABLE HOVEDINGREDIENS(
HI_ID INT PRIMARY KEY,
HI_NAVN VARCHAR2(30) NOT NULL
);
CREATE TABLE KATEGORI(
KAT_ID INT PRIMARY KEY,
KAT_NAVN VARCHAR2(20) NOT NULL
);
CREATE TABLE FORFATTER(
FORFATTER_ID INT PRIMARY KEY,
FORFATTER_NAVN VARCHAR2(20),
FORFATTER_EFTERNAVN VARCHAR2(20)
);
CREATE TABLE KOGEBOG(
KOGE_ID INT PRIMARY KEY,
TITEL VARCHAR(30),
FORFATTER_ID INT,
FOREIGN KEY (FORFATTER_ID) REFERENCES FORFATTER
);

CREATE TABLE OPSKRIFT(
OPSKRIFT_ID INT PRIMARY KEY,
OP_NAVN VARCHAR(40),
KOMMENTAR VARCHAR (1000),
HI_ID INT,
KAT_ID INT,
KOGE_ID INT,
FORFATTER_ID INT,
FOREIGN KEY (HI_ID) REFERENCES HOVEDINGREDIENS,
FOREIGN KEY (KAT_ID) REFERENCES KATEGORI,
FOREIGN KEY (KOGE_ID) REFERENCES KOGEBOG,
FOREIGN KEY (FORFATTER_ID) REFERENCES FORFATTER
);

CREATE TABLE OPSKRIFTSBILLEDE(
BILLEDE_ID INT PRIMARY KEY,
CONTENT_TYPE VARCHAR2(80) NOT NULL,
IMAGE BLOB,
OPSKRIFT_ID INT,
FOREIGN KEY(OPSKRIFT_ID) REFERENCES OPSKRIFT
);
CREATE TABLE OPSKRIFTTEKST(
TEKST_ID INT PRIMARY KEY,
CONTENT_TYPE VARCHAR2(80) NOT NULL,
IMAGE BLOB,
OPSKRIFT_ID INT,
FOREIGN KEY(OPSKRIFT_ID) REFERENCES OPSKRIFT
);

INSERT INTO BRUGER (BRUGER_ID, FORNAVN, EFTERNAVN, PASSWORD) VALUES (BRUGER_ID_SEQUENCE.NEXTVAL, 'Pernille', 'Jacobsen', '123');








COMMIT;













