INSERT INTO KATEGORI(KAT_ID, KAT_NAVN) VALUES (KAT_ID_SEQUENCE.NEXTVAL, 'Forret');
INSERT INTO KATEGORI(KAT_ID, KAT_NAVN) VALUES (KAT_ID_SEQUENCE.NEXTVAL, 'Hovedret');
INSERT INTO KATEGORI(KAT_ID, KAT_NAVN) VALUES (KAT_ID_SEQUENCE.NEXTVAL, 'Dessert');
INSERT INTO KATEGORI(KAT_ID, KAT_NAVN) VALUES (KAT_ID_SEQUENCE.NEXTVAL, 'Snack');
INSERT INTO KATEGORI(KAT_ID, KAT_NAVN) VALUES (KAT_ID_SEQUENCE.NEXTVAL, 'Snack/forret');
INSERT INTO KATEGORI(KAT_ID, KAT_NAVN) VALUES (KAT_ID_SEQUENCE.NEXTVAL, 'Kage');
INSERT INTO KATEGORI(KAT_ID, KAT_NAVN) VALUES (KAT_ID_SEQUENCE.NEXTVAL, 'Brød');
INSERT INTO KATEGORI(KAT_ID, KAT_NAVN) VALUES (KAT_ID_SEQUENCE.NEXTVAL, 'Boller');

INSERT INTO FORFATTER(FORFATTER_ID, FORFATTER_NAVN, FORFATTER_EFTERNAVN) VALUES (FORFATTER_ID_SEQUENCE.NEXTVAL, 'TEST1', 'TEST1');
INSERT INTO FORFATTER(FORFATTER_ID, FORFATTER_NAVN, FORFATTER_EFTERNAVN) VALUES (FORFATTER_ID_SEQUENCE.NEXTVAL, 'TEST2', 'TEST2');

INSERT INTO KOGEBOG(KOGE_ID, TITEL, FORFATTER_ID) VALUES (KOGE_ID_SEQUENCE.NEXTVAL, 'TEST1',2);
INSERT INTO KOGEBOG(KOGE_ID, TITEL, FORFATTER_ID) VALUES (KOGE_ID_SEQUENCE.NEXTVAL, 'TEST2',3);

INSERT INTO HOVEDINGREDIENS(HI_ID, HI_NAVN) VALUES(HI_ID_SEQUENCE.NEXTVAL, 'Fjerkræ');
INSERT INTO HOVEDINGREDIENS(HI_ID, HI_NAVN) VALUES(HI_ID_SEQUENCE.NEXTVAL, 'Okse');
INSERT INTO HOVEDINGREDIENS(HI_ID, HI_NAVN) VALUES(HI_ID_SEQUENCE.NEXTVAL, 'Kalv');
INSERT INTO HOVEDINGREDIENS(HI_ID, HI_NAVN) VALUES(HI_ID_SEQUENCE.NEXTVAL, 'Lam');
INSERT INTO HOVEDINGREDIENS(HI_ID, HI_NAVN) VALUES(HI_ID_SEQUENCE.NEXTVAL, 'Vildt');
INSERT INTO HOVEDINGREDIENS(HI_ID, HI_NAVN) VALUES(HI_ID_SEQUENCE.NEXTVAL, 'Pølser');
INSERT INTO HOVEDINGREDIENS(HI_ID, HI_NAVN) VALUES(HI_ID_SEQUENCE.NEXTVAL, 'Marcipan');
INSERT INTO HOVEDINGREDIENS(HI_ID, HI_NAVN) VALUES(HI_ID_SEQUENCE.NEXTVAL, 'Frugt');
INSERT INTO HOVEDINGREDIENS(HI_ID, HI_NAVN) VALUES(HI_ID_SEQUENCE.NEXTVAL, 'Rodfrugter');
INSERT INTO HOVEDINGREDIENS(HI_ID, HI_NAVN) VALUES(HI_ID_SEQUENCE.NEXTVAL, 'Fisk');
INSERT INTO HOVEDINGREDIENS(HI_ID, HI_NAVN) VALUES(HI_ID_SEQUENCE.NEXTVAL, 'Skaldyr');
COMMIT;

